### ISSUE TITLE
Theft Rewards

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc-spec#50]
With the removal of SLA, we had decided to reward valid theft reports from the liquidated Vault's collateral. Currently this is a fixed percentage of the Vault's total collateral which is very beneficial on over-collateralization and less so otherwise. A significant reward will also negatively affect the liquidation redeem (implicit) exchange rate, which may prevent users from burning interBTC.

Question: should we upper-bound the total theft rewards? Or is there some other scheme?

See also: https://github.com/interlay/interbtc/pull/210

**Comment by nud3l** [comment]
Agree that we should upper-bound the reporter reward in favor of increasing the available collateral to burn from the liquidation vault.

In consideration of multi-collateral, we will likely need different upper bounds though depending on the currency. To circumvent that problem, I think best to express the upper bound in BTC terms to ensure we use consistent upper bounds across different currencies based on current exchange rates.

My proposal is 0.1 BTC upper bound, but have this be updateable by governance.

What say you @gregdhill @sander2 ?
